// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2nJjdNytv-IE3zgJ4OoszQ2sQ4F3-dQM',
    appId: '1:755503474490:web:8859febd3f709cc8825203',
    messagingSenderId: '755503474490',
    projectId: 'green-pass-nsbm',
    authDomain: 'green-pass-nsbm.firebaseapp.com',
    storageBucket: 'green-pass-nsbm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE3A7x8qxD9MjVlQmTbu-nOrgYyU9rsBk',
    appId: '1:755503474490:android:f4b61ab4440a41ff825203',
    messagingSenderId: '755503474490',
    projectId: 'green-pass-nsbm',
    storageBucket: 'green-pass-nsbm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjz0b8rFiFu-AJSyySETDIMzsgx5HpTYo',
    appId: '1:755503474490:ios:d08c9f4bca550dbe825203',
    messagingSenderId: '755503474490',
    projectId: 'green-pass-nsbm',
    storageBucket: 'green-pass-nsbm.appspot.com',
    iosBundleId: 'com.greenpass.greenPass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjz0b8rFiFu-AJSyySETDIMzsgx5HpTYo',
    appId: '1:755503474490:ios:db6296950e3f114d825203',
    messagingSenderId: '755503474490',
    projectId: 'green-pass-nsbm',
    storageBucket: 'green-pass-nsbm.appspot.com',
    iosBundleId: 'com.greenpass.greenPass.RunnerTests',
  );
}
